
package com.exlibris.dps;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "FixityEventException", targetNamespace = "http://dps.exlibris.com/")
public class FixityEventException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FixityEventException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FixityEventException_Exception(String message, FixityEventException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public FixityEventException_Exception(String message, FixityEventException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.exlibris.dps.FixityEventException
     */
    public FixityEventException getFaultInfo() {
        return faultInfo;
    }

}
