
package com.exlibris.dps;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidCMSSystemException", targetNamespace = "http://dps.exlibris.com/")
public class InvalidCMSSystemException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidCMSSystemException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InvalidCMSSystemException_Exception(String message, InvalidCMSSystemException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InvalidCMSSystemException_Exception(String message, InvalidCMSSystemException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.exlibris.dps.InvalidCMSSystemException
     */
    public InvalidCMSSystemException getFaultInfo() {
        return faultInfo;
    }

}
