
package com.exlibris.dps;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NotInPermanentException", targetNamespace = "http://dps.exlibris.com/")
public class NotInPermanentException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NotInPermanentException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NotInPermanentException_Exception(String message, NotInPermanentException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public NotInPermanentException_Exception(String message, NotInPermanentException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.exlibris.dps.NotInPermanentException
     */
    public NotInPermanentException getFaultInfo() {
        return faultInfo;
    }

}
